export const TRADE_TOKEN_ADDRESS = "0xd87ba7a50b2e7e660f678a895e4b72e7cb4ccd9c";
const WEAVR = process.env.VUE_APP_WEAVR_ADDRESS;
const FRBC = process.env.VUE_APP_TOKEN_ADDRESS;
const THREAD_DEPLOYER = process.env.VUE_APP_THREAD_DEPLOYER_ADDRESS;
const BOND = process.env.VUE_APP_BOND_ADDRESS;
const BEACON = process.env.VUE_APP_BEACON_ADDRESS;
const FRABRIC_CODE = process.env.VUE_APP_FRABRIC_CODE_ADDRESS;
export const CONTRACTS = {
  WEAVR,
  FRBC,
  THREAD_DEPLOYER,
  BOND,
  BEACON,
  FRABRIC_CODE,
};
